### ISSUE TITLE
Helm Proxy: Nexus converts string to number in index.yaml causing Helm repo add to fail

### ISSUE THREAD

**Issue by ncouse** [sonatype/nexus-public#138]
# Helm Proxy: Nexus converts string to number in index.yaml causing Helm repo add to fail

This is a based on `NEXUS-36868`. I am re-creating here for public visibility and tracking, and comments, and requests for more information. 

## What problem are you trying to solve?

If I have a Helm proxy set up to point to a remote Helm repository, there are cases where values in the index.yaml file get converted causing `helm repo add` to output an error as it tries to parse the `index.yaml` file provided by Nexus.

```plaintext
Error: looks like "http://localhost:8182/repository/helm-test/" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal number into Go struct field ChartVersion.entries.appVersion of type string
```

More details below, but in summary, this is caused by certain chart metadata fields containing quoted strings that could be interpreted as number. In that case Nexus creates an incorrect proxied version of `index.yaml`. This proxied file cannot be read by the Helm CLI.

> **This stops the entire proxy repository being able to be used, due to a single new valid chart added on the remote repository. Therefore I think this is a critical issue.**

## Do you have a workaround you are using at present?

"Fixing" the chart metadata on the remote repository is the only fix. Note that the chart metadata is absolutely valid as per spec. More details below.

This can be done on repositories that we control, but is very cumbersome, and we shouldn't have to, as the charts are valid. Also, charts with metadata that causes an issue with Nexus could be added at anytime.

There is no option if we do not control the remote repository.

In summary, there is no real workaround.

## What feature or behavior is this required for?

This is required to proxy a remote Helm repository. This remote repository may be a corporate repository.

## How could we solve this issue? (Not knowing is okay!)

Fix the code that parses the `index.yaml` metadata. :)

## Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

I have successfully and simply reproduced this with Nexus OSS containers connected to remote Helm repository.

This was originally reported to us by customers using Nexus to connect to a corporate Helm repository. They would commonly use Nexus OSS in deployment environments, which would proxy to various remote Helm repositories, include corporate repositories.

## Anything else?

This is most likely to happen with `appVersion`, which is a string, because often developers add number style strings.

I have tested this in 3.53.1, but also is present in several earlier versions that I have tested since it was noticed.

In my case, I noticed this happening when `appVersion` was set to a quoted string, but where the string could be interpreted as a number. However it was only in the case where the number string contained an underscore.

For example, there was a chart on the remote Helm repository where the appVersion was set to something like '22.09_01'. Note that the remote index file has this value quoted, so it should be  interpreted as a string.

When I set up the Helm proxy in Nexus, and try to add try to do a `helm repo add`, I get as above.

Looking at this further, I see that the `index.yaml` from Nexus returns the appVersion **unquoted**, so it is interpreted as a number, and therefore it explains the Helm error.

---

I did some tests with a `index.yaml` file on a web server for some quick testing.

Setting a hard-coded index file on my test remote repository...

```yaml
apiVersion: v1
entries:
  my-chart:
  - apiVersion: v1
    name: my-chart
    description: 'My Chart'
    version: 1.0.0
    created: 2023-01-01T00:00:00.000Z
    appVersion: '22.09_01'
    digest: 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
    urls:
    - my-chart-1.0.0.tgz
```

When Nexus returns the index file, you notice that appVersion value is not unquoted.

```yaml
apiVersion: v1
entries:
  my-chart:
  - apiVersion: v1
    name: my-chart
    description: 22.09_01
    version: 1.0.0
    created: 2023-01-01T00:00:00.000Z
    appVersion: 22.09_01
    digest: 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
    urls:
    - my-chart-1.0.0.tgz
```

This seems to be the case for any number with an underscore in it. A number without an underscore such as 22.09 will remain quoted in the Nexus output.

A little more testing shows that it doesn't matter if the original index value is quoted or not.
However an unquoted number, without underscores, conveniently does get quoted when proxied.

|Original Value|Proxied Value|
|--------------|-------------|
|22.09_01      |22.09_01     |
|'22.09_01'    |22.09_01     |
|"22.09_01"    |22.09_01     |
|22.09         |"22.09"      |
|22            |"22"         |

---

The effect of this is that is some user sets the appVersion (or any other string field) to a number with an underscore, then it cannot be used via Nexus.

The appVersion is this case was correct, and was quoted. The Helm proxy had been in use for some time, and suddenly the Nexus proxy repo could no longer be used due to a new chart on the remote repository (which had a correct value).

This stops the entire proxy repository being able to be used, due to a single new valid chart added on the remote repository.

It is quite likely a someone may use an appVersion such as the example I provided. In this case is looks like the remote chart was using an underscore to indicate a patch. Therefore I could see this issue as potentially quite common.
