### ISSUE TITLE
Nexus not generating annotations in index.yaml file for charts

### ISSUE THREAD

**Issue by steporter** [sonatype/nexus-public#171]
* What problem are you trying to solve?
    When loading a chart to nexus the index.yaml file is autogenerated which is great, however the index.yaml file does not include the annotations section of the Chart.yaml.

    Code autogenerated from nexus for index.yaml
    ```
    apiVersion: v1
    entries:
      test:
      - name: test
        description: A Helm chart for Kubernetes
        version: 0.1.0
        created: 2023-06-20T12:33:46.796Z
        appVersion: 1.16.0
        digest: 2fc3de50dd31205711b7218ba559065a924c25c8779f66da378287c53a6ed60b
        urls:
        - test-0.1.0.tgz
    generated: 2023-06-20T12:33:47.800Z
    ```

    Code generated from `helm repo index` command (this is the expected behavior)
    ```
    apiVersion: v1
    entries:
      test:
      - annotations:
          custom.config/opt1: value1
          custom.config/opt2: value2
          custom.config/opt3: value3
          custom.config/opt4: value4
        apiVersion: v2
        appVersion: 1.16.0
        created: "2023-06-20T08:29:19.627985-04:00"
        description: A Helm chart for Kubernetes
        digest: 2fc3de50dd31205711b7218ba559065a924c25c8779f66da378287c53a6ed60b
        name: test
        type: application
        urls:
        - test-0.1.0.tgz
        version: 0.1.0
    generated: "2023-06-20T08:29:19.626441-04:00"
    ```

* Do you have a workaround you are using at present?
    No

* What feature or behavior is this required for?
    We need the generated index.yaml file to provide the annotations when it is generated as we look at those values before we pull the chart.
 
* How could we solve this issue? (Not knowing is okay!)
   Enable the generation of annotations in the index.yaml file

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
    Version of Nexus is OSS 3.51.0-01, running on RHEL8.8, no database as this is OSS version
