### ISSUE TITLE
Problem with "unknown blob" Error in Nexus 3

### ISSUE THREAD

**Issue by Majidahmadi** [sonatype/nexus-public#264]
I'm facing an issue with Nexus 3 repository today. When I attempted to pull Docker images from this repository, I encountered an "unknown blob" error. This issue didn't exist two days ago, and everything was working fine.

I have followed all the necessary steps for Docker requests and ensured that the Nexus 3 repository is in a healthy state. However, this mysterious error persists.

Has anyone experienced this error or can provide guidance on how to resolve it?

Any guidance or suggestions regarding this matter would be greatly appreciated. Thank you!

**Comment by Majidahmadi** [comment]
My Nexus 3 docker compose is:

```
version: "2"

services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - /nexus-data:/nexus-data
    ports:
      - 8081:8081
      - 5050:5050
      - 5060:5060
      - 18079:18079
      - 18080:18080
```

My error is:
```
# docker pull docker.mydomain.com/redis:7.0.2-alpine
7.0.2-alpine: Pulling from redis
2408cc74d12b: Pulling fs layer 
e90389148883: Pulling fs layer 
c6c08b6ea4d5: Downloading 
a1a4b4673a23: Waiting 
e14aa32bdd63: Waiting 
abe61b7e68d2: Waiting 
unknown blob
```

My Nexus details:
```
Version | 3.61.0-02
Edition | OSS
Build Revision | a992e3ff935cc93dccc988d027471bd71889cab5
Build Timestamp | 2023-10-04-1409-13954
```
