### ISSUE TITLE
Unable to scrape metrics using Victoriametrics VMServiceScrape

### ISSUE THREAD

**Issue by jahnavisana2812** [sonatype/nexus-public#371]
Hello,

Our Grafana setup utilizes VictoriaMetrics, a Prometheus-compatible system. I'm currently attempting to scrape the metrics exposed on `/service/metrics/prometheus`, but encountering login issues resulting in a 500 error. Below, you'll find the configuration for the `vmservicescrape` component I'm using, along with the documentation I've referenced. Your prompt assistance would be greatly appreciated. Thank you.
https://help.sonatype.com/en/support-features.html

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: nexus-metrics
  namespace: nexus
spec:
  endpoints:
    - interval: 5s
      basicAuth:
        password:
          key: *******
        username:
          key: developer
      vm_scrape_params:
        proxy_client_config:
          basic_auth:
            password:
              key: ******
            username:
              key: developer
      path: /service/metrics/prometheus
      port: nexus
      scheme: http
  jobLabel: nxrm
  namespaceSelector:
    matchNames:
      - nexus
  selector: 
    matchLabels:
      app: nexus
```
