### ISSUE TITLE
Regression on nexus-context-path when serving nexus from custom base url (3.70.0-03)

### ISSUE THREAD

**Issue by shkuviak** [sonatype/nexus-public#452]
* What problem are you trying to solve?

I am serving nexus via a reverse proxy (traefik ingress controller):
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nexus
  namespace: nexus
spec:
  rules:
  - http:
      paths:
      - path: /nexus
        pathType: Prefix
        backend:
          service:
            name: nexus-repository
            port:
              name: webui
```

I use `nexus-context-path=/nexus` in `/nexus-data/etc/nexus.properties` to serve nexus from `/nexus`.

It was working well using **Nexus 3.64**. 

I upgraded to **Nexus 3.70** and issues appeared in web interface.

UI tries to access **https://my-domain/service/extdirect** instead of **https://my-domain/nexus/service/extdirect** 

After some investigations i saw that this issue was **only caused by requests from** `ExtAPIUtils.js`.

![image](https://github.com/user-attachments/assets/a7dc5ad1-3881-470e-a775-1c1bf0939a55)

* Impact on UI

    - Welcome page
    - Component upload page
    - Create role admin page
    - Maybe more

* Do you have a workaround you are using at present?

If i create an ingress **AddPrefix** rule to rewrite /service/* route as /nexus/service/*, it is working again.

* What feature or behavior is this required for?

Serving Nexus from a custom base path.

* How could we solve this issue? (Not knowing is okay!)

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

Version: 3.70.0-03
Operating system: sonatype/nexus3:3.70.0 docker image on top of k8s cluster.

* Anything else?
